@startuml
left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Гость" as Guest
actor "Покупатель" as Buyer
actor "Платежная система" as Payment
actor "Служба доставки" as Delivery

Buyer --|> Guest

rectangle "Lamoda.ru" {
  usecase "Просматривать\nглавную страницу" as UC1
  usecase "Искать товар" as UC2
  usecase "Просматривать\nкаталог" as UC3
  usecase "Фильтровать и\nсортировать товары" as UC4
  usecase "Открывать карточку\nтовара" as UC5
  usecase "Выбирать размер,\nцвет и количество" as UC6
  usecase "Добавлять товар\nв корзину" as UC7
  usecase "Просматривать и\nредактировать корзину" as UC8
  usecase "Авторизоваться /\nзарегистрироваться" as UC9
  usecase "Добавлять товар\nв избранное" as UC10
  usecase "Оформлять заказ" as UC11
  usecase "Выбирать способ\nдоставки" as UC12
  usecase "Оплачивать заказ" as UC13
  usecase "Отслеживать заказ" as UC14
}

Guest --> UC1
Guest --> UC2
Guest --> UC3
Guest --> UC4
Guest --> UC5
Guest --> UC8
Guest --> UC9

Buyer --> UC6
Buyer --> UC7
Buyer --> UC8
Buyer --> UC10
Buyer --> UC11
Buyer --> UC14

UC3 .> UC4 : <<include>>
UC5 .> UC6 : <<extend>>
UC5 .> UC7 : <<extend>>
UC11 .> UC8 : <<include>>
UC11 .> UC9 : <<include>>
UC11 .> UC12 : <<include>>
UC11 .> UC13 : <<include>>

Payment --> UC13
Delivery --> UC12
Delivery --> UC14
@enduml

